import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Activity, CheckCircle2, Clock3, RotateCcw, XCircle } from 'lucide-react';
import { apiFetch } from '../../lib/api';

type QueueJob = { id: string; job_name: string; status: string; attempts: number; max_attempts: number; last_error: string | null; created_at: string };
type JobRun = { id: string; job_name: string; status: 'running' | 'succeeded' | 'failed'; started_at: string; duration_ms: number | null; processed_count: number | null; error_message: string | null };

export default function Automacoes() {
  const queryClient = useQueryClient();
  const runsQuery = useQuery({ queryKey: ['admin-automation-jobs'], refetchInterval: 30000, queryFn: async () => { const response = await apiFetch('/api/admin/automation-jobs?limit=100'); if (!response.ok) throw new Error((await response.json()).error ?? 'Falha ao carregar histórico'); return (await response.json()) as { runs: JobRun[] }; } });
  const queueQuery = useQuery({ queryKey: ['admin-automation-queue'], refetchInterval: 15000, queryFn: async () => { const response = await apiFetch('/api/admin/automation-queue'); if (!response.ok) return { jobs: [] as QueueJob[] }; return await response.json() as { jobs: QueueJob[] }; } });
  const requeue = useMutation({ mutationFn: async (id: string) => { const response = await apiFetch(`/api/admin/automation-queue/${id}/requeue`, { method: 'POST' }); if (!response.ok) throw new Error('Falha ao reprocessar'); }, onSuccess: () => queryClient.invalidateQueries({ queryKey: ['admin-automation-queue'] }) });
  const runs = runsQuery.data?.runs ?? [];
  const statusIcon = (status: JobRun['status']) => status === 'succeeded' ? <CheckCircle2 className="text-emerald-400" size={18} /> : status === 'failed' ? <XCircle className="text-red-400" size={18} /> : <Clock3 className="text-amber-400" size={18} />;
  return <section className="space-y-5"><div><h1 className="text-2xl font-bold text-white">Automações</h1><p className="mt-1 text-sm text-slate-400">Histórico, fila, lock distribuído e dead-letter dos jobs.</p></div>
    {runsQuery.isLoading && <p className="text-slate-400">Carregando histórico…</p>}
    {runsQuery.error && <div className="rounded-lg border border-amber-500/30 bg-amber-500/10 p-4 text-amber-200">{(runsQuery.error as Error).message}</div>}
    {!runsQuery.isLoading && !runsQuery.error && <><div className="overflow-hidden rounded-xl border border-[#1C3050] bg-[#132540]"><div className="flex items-center gap-2 border-b border-[#1C3050] px-4 py-3 text-slate-300"><Activity size={18} /> Últimas execuções</div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-slate-500"><th className="px-4 py-3">Job</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Início</th><th className="px-4 py-3">Duração</th><th className="px-4 py-3">Processados</th><th className="px-4 py-3">Erro</th></tr></thead><tbody>{runs.map((run) => <tr key={run.id} className="border-t border-[#1C3050] text-slate-300"><td className="px-4 py-3 font-medium">{run.job_name}</td><td className="px-4 py-3"><span className="inline-flex items-center gap-2">{statusIcon(run.status)}{run.status}</span></td><td className="px-4 py-3">{new Date(run.started_at).toLocaleString('pt-BR')}</td><td className="px-4 py-3">{run.duration_ms == null ? '—' : `${run.duration_ms} ms`}</td><td className="px-4 py-3">{run.processed_count ?? '—'}</td><td className="max-w-xs truncate px-4 py-3 text-red-300">{run.error_message ?? '—'}</td></tr>)}</tbody></table></div>{!runs.length && <p className="p-6 text-slate-400">Nenhuma execução registrada.</p>}</div>
    <div className="overflow-hidden rounded-xl border border-[#1C3050] bg-[#132540]"><div className="flex items-center gap-2 border-b border-[#1C3050] px-4 py-3 text-slate-300"><RotateCcw size={18} /> Fila e dead-letter</div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-slate-500"><th className="px-4 py-3">Job</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Tentativas</th><th className="px-4 py-3">Erro</th><th className="px-4 py-3"></th></tr></thead><tbody>{(queueQuery.data?.jobs ?? []).map((job) => <tr key={job.id} className="border-t border-[#1C3050] text-slate-300"><td className="px-4 py-3">{job.job_name}</td><td className="px-4 py-3">{job.status}</td><td className="px-4 py-3">{job.attempts}/{job.max_attempts}</td><td className="max-w-xs truncate px-4 py-3 text-red-300">{job.last_error ?? '—'}</td><td className="px-4 py-3">{job.status === 'dead_letter' && <button onClick={() => requeue.mutate(job.id)} className="inline-flex items-center gap-1 text-emerald-300 hover:text-emerald-200"><RotateCcw size={14} /> Reprocessar</button>}</td></tr>)}</tbody></table></div>{!(queueQuery.data?.jobs?.length) && <p className="p-6 text-slate-400">Nenhum job na fila.</p>}</div></>}
  </section>;
}